name: Docker Image CI/CD

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  TEST_TAG_BASE: ${{ github.repository }}:test
  TEST_TAG_NPM: ${{ github.repository }}:test-npm

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker meta base
        id: meta-base
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{major}}.{{minor}}

      - name: Docker meta npm
        id: meta-npm
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=auto
            suffix=-npm,onlatest=true

      - name: Build and Export Base to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG_BASE }}

      - name: Build and Export NPM Image to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: npm/Dockerfile
          load: true
          tags: ${{ env.TEST_TAG_NPM }}

      - name: Check hugo executable
        run: docker run --rm -u hugo ${{ env.TEST_TAG_BASE }} hugo version

      - name: Check minify executable
        run: docker run --rm -u hugo ${{ env.TEST_TAG_BASE }} minify --version

      - name: Check npm executable
        run: docker run --rm -u hugo ${{ env.TEST_TAG_NPM }} npm --version

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request' && github.ref != 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: xdevbase
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Base Docker Image
        if: github.event_name != 'pull_request' && github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta-base.outputs.tags }}
          labels: ${{ steps.meta-base.outputs.labels }}

      - name: Build and Push NPM Docker Image
        if: github.event_name != 'pull_request' && github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: npm/Dockerfile
          push: true
          tags: ${{ steps.meta-npm.outputs.tags }}
          labels: ${{ steps.meta-npm.outputs.labels }}
